### ISSUE TITLE
useField needless rerenders

### ISSUE THREAD

**Issue by lishine** [JoviDeCroock/Hooked-Form#96]
When typing into one field, it rerenders another field, as in the codesandbox.
https://codesandbox.io/s/hooked-form-2rfk2

**Comment by lishine** [comment]
I suppose that this rerenders the field on each form change

**Comment by JoviDeCroock** [comment]
Those rerenders are related to react-refresh as you can see this library uses changedBits to make context propagation disabled.

**Comment by lishine** [comment]
Oh, so that secrete feature, didn't know about it. Understood.
But what do you mean by react-refresh and how it is related to dev-build? If it not rerenders because of context, then why it rerenders?

**Comment by JoviDeCroock** [comment]
@lishine it's the replacement for hot-reload.

I'll see if I can reproduce it with the React version you use there but it would be odd

**Comment by JoviDeCroock** [comment]
I can't reprodue this in a test. I found one potential issue that I'm resolving as we speak in https://github.com/JoviDeCroock/Hooked-Form/compare/master...update-deps

**Comment by lishine** [comment]
About the refresh.
I still don't get it how is it related to runtime behaviour. Hot reload reacts to code changes.
You mean, it injects some code in Dev? Please point me to a link with info.

**Comment by lishine** [comment]
About the context granularity.
This is why implementation with Mobx or similar libs is simpler.

**Comment by JoviDeCroock** [comment]
The compat with refresh is fixed in 4.2.2, there are no elaborate explanations on how it works.

Your best bet is reading how an integration works like webpack-react-refresh,... I tried making one in the start. It basically only swaps out the changed part. This can lead to residual stuff being left in.

MobX is slower in deriving updates tho since proxy and defineProperty have a cost of their own (in both size and execution). That being said I know how we can optimize, we can replace deriveKeys with deriveChangedKeys. There’s room foor that small size increase.

**Comment by JoviDeCroock** [comment]
I've been doing a lot of performance improvements, these should have significant impact. Thanks for bringing me up to speed @lishine I'll try to get the 4.2.3 release out tomorrow!

Making issues is the most helpful anyone can be so big props to you!

**Comment by JoviDeCroock** [comment]
@all-contributors please add lishine for bug

**Comment by lishine** [comment]
Thank you for adding me as a contributor.
But I still wondering about the rerendering.
Still not understanding the react-refresh thing, is it some CRA stuff and using maybe parcel it will be solved? 
 I checked the new version in codesandbox, it still has the extra  rerenders. Also the performance codesandbox makes extra rerenders with optimised final-form.
Can you suggest a way to check rerenders?
Btw stumbled across cool validation lib
https://github.com/vriad/zod

**Comment by JoviDeCroock** [comment]
Yes I know `zod`. I mean do your research, it's hot swapping which just causes react-specific internals to be swapped out. This isn't possible automatically since code itself isn't observable so these call `this.forceUpdate()` every dev build will have these, prod is the most accurate benchmarking tool

**Comment by JoviDeCroock** [comment]
I wouldn't really worry about perf if I was you, you can see that there are measures in place to be more performant than general form-libraries and it's comparable to `final-form` which is close to `uncontrolled` inputs.

**Comment by lishine** [comment]
Actually now it works great! No extra rerenders

**Comment by JoviDeCroock** [comment]
@lishine There's also a beta with a convenience validator, the second argument to `useField` can be an optional validation function for that field. Might be a nice addition, doing a beta for it atm.

```
useField('name', (name) => name === 'x' ? 'error' : undefined)
```

**Comment by lishine** [comment]
There is the above approach and there is the central validation scheme approach.
I preferred the central approach, but then it does validation of the whole form on each field change.
In that regard the above approach probably better.
I would still attach the validation centrally but make sure only the appropriate field is validated. I know Formik have a PR to do it with yup haven't succeeded yet. 
I will try to use zod for validation.

**Comment by JoviDeCroock** [comment]
Yes, so you are sure in `hooked-form` only the appropriate fields are rerendered due to https://github.com/JoviDeCroock/Hooked-Form/blob/master/src/Form.tsx#L110

**Comment by lishine** [comment]
About the performance test with the codesandbox with the latest version of hooked-form - typing in the field - onchange:
hooked-form 0.8ms
final-form 0.2ms

Btw the initial render with hooked-form is x2 fast as final-form
